---

- name: Set authorized key for root user copying it from current user
  authorized_key:
    user: "root"
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Allow connection as root user
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin prohibit-password'
  notify:
  - restart sshd

