---

# enable i2c, TODO

- name: Install python-smbus library
  apt:
    name: python-smbus

- name: Install lm-sensors
  apt:
    name: lm-sensors

- name: load shtc1 kernel module
  modprobe:
    name: shtc1
    state: present

- name: load shtc1 kernel module at boot time
  copy:
    content: 'shtc1'
    dest: /etc/modules-load.d/shtc1.conf
    owner: root
    group: root
    mode: 0755

- name: insert/update i2c stuff in /etc/rc.local
  blockinfile:
    path: /etc/rc.local
    block: |
      # register temperature and humidity at i2c address 0x70
      echo shtc1 0x70 > /sys/bus/i2c/devices/i2c-1/new_device

- name: copy local voltage.py file to remote rbpi
  copy:
    src: ./files/voltage.py
    dest: /bin/voltage.py
    owner: root
    group: root
    mode: 0755

- name: install voltage service systemd unit file
  template:
    src: voltage.service.j2
    dest: /etc/systemd/system/voltage.service
    owner: root
    group: root
    mode: 0644

- name: install voltage timer systemd unit file
  template:
    src: voltage.timer.j2
    dest: /etc/systemd/system/voltage.timer
    owner: root
    group: root
    mode: 0644

- name: start voltage.timer
  systemd:
    name: voltage.timer
    state: started
    enabled: yes
    daemon_reload: yes


- name: copy local env.sh file to remote rbpi
  copy:
    src: ./files/env.sh
    dest: /bin/env.sh
    owner: root
    group: root
    mode: 0755

- name: install env service systemd unit file
  template:
    src: env.service.j2
    dest: /etc/systemd/system/env.service
    owner: root
    group: root
    mode: 0644

- name: install env timer systemd unit file
  template:
    src: env.timer.j2
    dest: /etc/systemd/system/env.timer
    owner: root
    group: root
    mode: 0644

- name: start env.timer
  systemd:
    name: env.timer
    state: started
    enabled: yes
    daemon_reload: yes
