---

- name: Install zabbix agent
  apt:
    name: zabbix-agent

- name: Create zabbix agent config
  template:
    src: zabbix-agentd.conf.j2
    dest: /etc/zabbix/zabbix_agentd.conf
    owner: root
    group: root
    mode: 0644
  notify:
  - restart zabbix-agent

- name: Start zabbix-agent service
  service:
    name: zabbix-agent
    state: started
    enabled: yes

